title: "2FA Directory"
icon: "/icons/icon.svg"
copyright: "2factorauth"
languageCode: "en"
DefaultContentLanguage: "en"
disableKinds: ["taxonomy", "taxonomyTerm"]
disableHugoGeneratorInject: true
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true

params:
  default:
    description: "List of sites with two factor auth support which includes SMS, email, phone calls, hardware, and software."
    github: "2factorauth/twofactorauth"
    theme_color: "#38CCCC"
    icon_path: "https://api.2fa.directory/icons/"
    mastodon: "https://infosec.exchange/@2factorauth"

  twitter:
    handle: "2faorg"
    card: "/icons/social-card.png"

outputFormats:
  manifest:
    name: "manifest"
    baseName: "manifest"
    mediaType: "application/json"
    notAlternative: true

outputs:
  home:
    - "MANIFEST"
